name: Conventional Commit

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  validate-pr-title:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR Title Conforms To Conventional Commit Message
        uses:  ytanikin/pr-conventional-commits@1.4.0
        with:
          ## cspell:words prefeature
          task_types: '["feature","prefeature","fix","docs","tests","build","ci","refactor","chore","revert","linter","types","style"]'
