name: Dependabot
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Merge sanctioned dependency-bump PRs automatically
    runs-on: ubuntu-latest
    if: |
      (github.event.pull_request.user.login == 'dependabot[bot]') &&
      (!github.event.pull_request.head.repo.fork)
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Fetch metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable "auto-merge" for non-major version updates # Assumes the repository requires checks to pass before merging
        if: |
          (steps.metadata.outputs.update-type == 'version-update:semver-patch') ||
          (steps.metadata.outputs.update-type == 'version-update:semver-minor')
        run: gh pr merge --squash --auto "$PR_URL"
      - name: 'Approve select dependencies for bump: patch'
        if: |
          contains(
            fromJSON('[
              "vue-tsc"
            ]'),
            steps.metadata.outputs.dependency-names
          )
          && (steps.metadata.outputs.update-type == 'version-update:semver-patch')
        run: gh pr review --approve "$PR_URL"
      - name: 'Approve select dependencies for bump: patch, minor'
        if: |
          contains(
            fromJSON('[
              "@eslint/markdown",
              "@stylistic/eslint-plugin",
              "@typescript-eslint/parser",
              "@types/node",
              "cypress",
              "eslint",
              "eslint-plugin-cypress",
              "eslint-plugin-vue",
              "typescript-eslint",
              "typescript",
              "vite",
            ]'),
            steps.metadata.outputs.dependency-names
          )
          && (
            (steps.metadata.outputs.update-type == 'version-update:semver-patch') ||
            (steps.metadata.outputs.update-type == 'version-update:semver-minor')
          )
        run: gh pr review --approve "$PR_URL"
