name: Docs

on:
  push:
    branches:
      - integration
      - release
  pull_request:
    branches:
      - integration
      - release

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check for changes to doc files
        uses: tj-actions/changed-files@v47
        id: changed-files
        with:
          files: |
            .github/workflows/docs.yml
            package.json
            **/*.md
          separator: ','
      - name: Lint the updated Markdown files
        id: lint-markdown-files
        uses: DavidAnson/markdownlint-cli2-action@v20
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          config: .markdownlint-cli2.yaml
          globs: >-
            ${{
              (
                contains(steps.changed-files.outputs.all_changed_files, '.github/workflows/docs.yml') ||
                contains(steps.changed-files.outputs.all_changed_files, 'package.json')
              )
              && '**/*.md'
              || steps.changed-files.outputs.all_changed_files
            }}
          separator: ','
        continue-on-error: true
      - name: If linter failed, highlight debug tools
        if: steps.lint-markdown-files.outcome == 'failure'
        run: |
          echo "::notice::Run \`npm run lint:docs\` in your dev environment to see which issues aren't automatically fixable."
          exit 1
