name: Node

on:
  push:
    branches:
      - integration
    paths:
      - '.github/workflows/node.yml' # Trigger workflow when it's modified
      - 'package.json'               # For dependency changes
      - 'package-lock.json'          # For nested dependency changes, like security updates
      - '**/*.js'                    # For scripts
      - '**/*.ts'                    # For scripts
      - '**/*.cjs'                   # For scripts
      - '**/*.cts'                   # For scripts
      - '**/*.mjs'                   # For scripts
      - '**/*.mts'                   # For scripts
      - '**/*.jsx'                   # For scripts
      - '**/*.tsx'                   # For scripts
      - '**/*.vue'                   # For single-file components that contain a script block
      - '!**/*.md'                   # Ignore markdown files (and their constituent fenced code blocks)
      - '!docs/**'                   # Ignore docs folder
  pull_request:
    branches:
      - integration
    paths:
      - '.github/workflows/node.yml' # Trigger workflow when it's modified
      - 'package.json'               # For dependency changes
      - 'package-lock.json'          # For nested dependency changes, like security updates
      - '**/*.js'                    # For scripts
      - '**/*.ts'                    # For scripts
      - '**/*.cjs'                   # For scripts
      - '**/*.cts'                   # For scripts
      - '**/*.mjs'                   # For scripts
      - '**/*.mts'                   # For scripts
      - '**/*.jsx'                   # For scripts
      - '**/*.tsx'                   # For scripts
      - '**/*.vue'                   # For single-file components that contain a script block
      - '!**/*.md'                   # Ignore markdown files (and their constituent fenced code blocks)
      - '!docs/**'                   # Ignore docs folder

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Lint, Compile, and Test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install all dependencies (which includes linters)
        run: npm clean-install
      - name: Run the linter
        id: lint
        run: npx eslint . --max-warnings 0 --cache
        continue-on-error: true
      - name: If linter fails, highlight debug tools
        if: steps.lint.outcome == 'failure'
        run: |
          echo "::notice::Enable lint-on-save in your editor for automatic fixes"
          echo "::notice::Run \`npm run lint\` in your dev environment for details about issues that aren't automatically fixable"
          exit 1
      - name: Run the compiler
        id: compile
        run: npx vue-tsc --build
        continue-on-error: true
      - name: If compilation fails, highlight debug tools
        if: steps.compile.outcome == 'failure'
        run: |
          echo "::notice::Run \`npx vue-tsc --build\` in your dev environment for details about compiler issues"
          exit 1
      - name: Run the unit tests
        id: test_units
        run: npm run test:unit
        continue-on-error: true
      - name: If unit tests fail, highlight debug tools
        if: steps.test_units.outcome == 'failure'
        run: |
          echo "::notice::Run \`npm run test:unit\` in your dev environment for a detailed report about failed unit tests"
          exit 1